### ISSUE TITLE
aioredis doesn't support Python version prior 3.5

### ISSUE THREAD

**Issue by vis7** [justdjango/justchat#15]
When I start to run by creating virtual environment and then 
`pip install -r requirements.txt`
I got error bellow
```
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting aioredis==1.2.0
  Downloading aioredis-1.2.0.tar.gz (150 kB)
     |████████████████████████████████| 150 kB 19 kB/s 
    ERROR: Command errored out with exit status 1:
     command: /home/vishvajeet/Desktop/Programming/django/environment/justchat-master/env/bin/python2.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-S35mTi/aioredis/setup.py'"'"'; __file__='"'"'/tmp/pip-install-S35mTi/aioredis/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-S35mTi/aioredis/pip-egg-info
         cwd: /tmp/pip-install-S35mTi/aioredis/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-S35mTi/aioredis/setup.py", line 15, in <module>
        raise RuntimeError("aioredis doesn't support Python version prior 3.5")
    RuntimeError: aioredis doesn't support Python version prior 3.5
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
It seems aioredis-1.2.0 does not support new version of python.
If possible then try to upgrade from existing version of 2.2 to 3.0.2
```

**Comment by saschametz** [comment]
You should use a newer python version (>= 3.5).

If you already have python 3 installed this command may work:
```
python3 -m pip install -r requirements.txt 
```
