### ISSUE TITLE
TemplateDoesNotExist at / App is not starting with localhost:8000

### ISSUE THREAD

**Issue by rajesh212** [justdjango/justchat#4]
python manage.py runserver 
Performing system checks...

System check identified no issues (0 silenced).
March 20, 2019 - 18:46:54
Django version 2.1.5, using settings 'justchat.settings'
Starting ASGI/Channels version 2.1.5 development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
HTTP GET /chat/ 200 [0.05, 127.0.0.1:52236]
HTTP GET /static/rest_framework/css/bootstrap-tweaks.css 200 [0.02, 127.0.0.1:52240]
HTTP GET /static/rest_framework/js/jquery-3.3.1.min.js 200 [0.02, 127.0.0.1:52252]
HTTP GET /static/rest_framework/css/prettify.css 200 [0.02, 127.0.0.1:52244]
HTTP GET /static/rest_framework/css/bootstrap.min.css 200 [0.02, 127.0.0.1:52236]
HTTP GET /static/rest_framework/css/default.css 200 [0.02, 127.0.0.1:52248]
HTTP GET /static/rest_framework/js/ajax-form.js 200 [0.02, 127.0.0.1:52256]
HTTP GET /static/rest_framework/js/bootstrap.min.js 200 [0.01, 127.0.0.1:52244]
HTTP GET /static/rest_framework/js/default.js 200 [0.01, 127.0.0.1:52252]
HTTP GET /static/rest_framework/js/csrf.js 200 [0.01, 127.0.0.1:52240]
HTTP GET /static/rest_framework/js/prettify-min.js 200 [0.01, 127.0.0.1:52248]
HTTP GET /static/rest_framework/img/grid.png 200 [0.00, 127.0.0.1:52248]
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/home/rajesh/justchat/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rajesh/justchat/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rajesh/justchat/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/home/rajesh/justchat/env/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/rajesh/justchat/env/lib/python3.6/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rajesh/justchat/env/lib/python3.6/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/home/rajesh/justchat/env/lib/python3.6/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
HTTP GET /favicon.ico 500 [0.04, 127.0.0.1:52248]
HTTP GET /chat/ 200 [0.05, 127.0.0.1:52248]
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/home/rajesh/justchat/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rajesh/justchat/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rajesh/justchat/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/home/rajesh/justchat/env/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/rajesh/justchat/env/lib/python3.6/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rajesh/justchat/env/lib/python3.6/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/home/rajesh/justchat/env/lib/python3.6/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
HTTP GET /favicon.ico 500 [0.04, 127.0.0.1:52248]
HTTP GET /api-auth/login/?next=/chat/ 200 [0.03, 127.0.0.1:52248]
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/home/rajesh/justchat/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rajesh/justchat/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rajesh/justchat/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/home/rajesh/justchat/env/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/rajesh/justchat/env/lib/python3.6/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rajesh/justchat/env/lib/python3.6/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/home/rajesh/justchat/env/lib/python3.6/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
HTTP GET /favicon.ico 500 [0.04, 127.0.0.1:52248]

**Comment by justdjango** [comment]
I cannot seem to replicate this error. Please provide clearly how you obtained this error and don't just paste the entire error code here.
